### ISSUE TITLE
请问 tab 页面切换是否有相关动画，能否在示例中添加

### ISSUE THREAD

**Issue by auven** [dreamback/vue-route-transition#1]

**Comment by dreamback** [comment]
这里的交互逻辑不一样。
参考原生APP，不建议做动画。

**Comment by auven** [comment]
试了一下 tab 嵌套路由，不会有动画，满足需求了。原先问这个问题，是担心在 tab 里也会有动画，体验感不好。

**Comment by 499596986** [comment]
现在的动画是每个页面都设定单个路由,   那如果想做成  嵌套路由的时候。怎么动画切换呢
